[build]
  command = "git clone --depth 1 --branch 3.19.6 https://github.com/flutter/flutter.git && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release"
  publish = "build/web"
  
