[build]
  command = "git clone https://github.com/flutter/flutter.git && cd flutter && git checkout stable && cd .. && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release"
  publish = "build/web"

[build.environment]
  # Set the Flutter version you want to use
  FLUTTER_VERSION = "3.19.6"
  
