name: sk_games_admin_panel
description: "Admin panel for SK Games Tournament App."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.5.0
  google_fonts: ^6.2.1
  # For saving login session in browser
  shared_preferences: ^2.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
